x = int(input("Enter a number: "))
y = int(input("Enter another number: "))
print("Addition: " , x+y)
print("Subtraction: " , x-y)
print("Multiplication: " , x*y)
print("Division: " , x/y)
print("Floor Division: " , x//y)
print("Modulus: " , x%y)
print("Exponentiation: " , x**y)
